---
- hosts: ios
  tasks:
  - ios_command:
      commands: show arp
    register: arp

- hosts: nxos
  tasks:
  - nxos_command:
      commands: show ip arp
    register: arp

- hosts: junos
  tasks:
  - junos_command:
      commands: show arp
    register: arp
